### ISSUE TITLE
Options Gui is broken

### ISSUE THREAD

**Issue by Swirln** [Swirln/DiscordBL#1]
![image](https://user-images.githubusercontent.com/25020307/33522360-58207136-d7b0-11e7-9af4-53d43c86587a.png)

**Comment by Swirln** [comment]
To replicate, just type in DiscordBL::OpenOptions();

**Comment by carat-ye** [comment]
Update from 999999 years later: still not fixed.

**Comment by carat-ye** [comment]
I hate you, myself.

**Comment by carrot512** [comment]
Agreed !

**Comment by Swirln** [comment]
Will not fix; removing options gui in new release
